import { useMemo, useState } from 'react'
import { Braces, Calculator, Copy, Grid3X3, Sigma } from 'lucide-react'
import { bitwise, determinant, identity, inverse, matrixAdd, matrixMultiply, matrixRank, parseDataset, programmerRepresentations, solveLinear, solveQuadratic, solveSystem2, statistics, transpose, type Matrix } from '../../core/lab'

type Tool = 'equations' | 'matrix' | 'statistics' | 'programmer'
const tools = [
  { id: 'equations' as const, name: 'Equation solver', description: 'Linear, quadratic, and two-variable systems', icon: Calculator },
  { id: 'matrix' as const, name: 'Matrix workspace', description: 'Core matrix operations up to 4 × 4', icon: Grid3X3 },
  { id: 'statistics' as const, name: 'Statistics', description: 'Descriptive analysis for pasted datasets', icon: Sigma },
  { id: 'programmer' as const, name: 'Programmer', description: 'Bases, bit widths, and bitwise operations', icon: Braces },
]

function EquationTool() {
  const [kind, setKind] = useState<'linear' | 'quadratic' | 'system'>('quadratic')
  const [values, setValues] = useState([1, -3, 2, 2, 1, 5])
  const result = useMemo(() => kind === 'linear' ? solveLinear(values[0], values[1]) : kind === 'quadratic' ? solveQuadratic(values[0], values[1], values[2]) : solveSystem2(values as [number, number, number, number, number, number]), [kind, values])
  const update = (index: number, value: number) => setValues((current) => current.map((item, i) => i === index ? value : item))
  return <div className="lab-tool equation-tool"><header><div><span className="eyebrow">Equation solver</span><h2>Solve and verify</h2></div><div className="segmented"><button className={kind === 'linear' ? 'active' : ''} onClick={() => setKind('linear')}>Linear</button><button className={kind === 'quadratic' ? 'active' : ''} onClick={() => setKind('quadratic')}>Quadratic</button><button className={kind === 'system' ? 'active' : ''} onClick={() => setKind('system')}>2 × 2 system</button></div></header>
    {kind === 'linear' ? <div className="equation-input"><input type="number" value={values[0]} onChange={(e) => update(0, Number(e.target.value))} aria-label="Coefficient a" /><i>x</i><span>+</span><input type="number" value={values[1]} onChange={(e) => update(1, Number(e.target.value))} aria-label="Coefficient b" /><span>= 0</span></div> : kind === 'quadratic' ? <div className="equation-input"><input type="number" value={values[0]} onChange={(e) => update(0, Number(e.target.value))} aria-label="Coefficient a" /><i>x²</i><span>+</span><input type="number" value={values[1]} onChange={(e) => update(1, Number(e.target.value))} aria-label="Coefficient b" /><i>x</i><span>+</span><input type="number" value={values[2]} onChange={(e) => update(2, Number(e.target.value))} aria-label="Coefficient c" /><span>= 0</span></div> : <div className="system-input">{[0, 3].map((offset, row) => <div key={offset}><input type="number" value={values[offset]} onChange={(e) => update(offset, Number(e.target.value))} aria-label={`Equation ${row + 1} x coefficient`} /><i>x</i><span>+</span><input type="number" value={values[offset + 1]} onChange={(e) => update(offset + 1, Number(e.target.value))} aria-label={`Equation ${row + 1} y coefficient`} /><i>y</i><span>=</span><input type="number" value={values[offset + 2]} onChange={(e) => update(offset + 2, Number(e.target.value))} aria-label={`Equation ${row + 1} result`} /></div>)}</div>}
    <div className="solution-panel">{'roots' in result ? <><span>Solution</span><strong>{result.kind === 'infinite' ? 'Infinitely many solutions' : result.kind === 'none' ? 'No solution' : result.roots.map((root) => `x = ${typeof root === 'number' ? Number(root.toPrecision(10)) : root}`).join('  ·  ')}</strong>{'discriminant' in result ? <p>Discriminant: {result.discriminant} · {result.discriminant > 0 ? 'two real roots' : result.discriminant === 0 ? 'one repeated root' : 'complex conjugate roots'}</p> : null}{'verification' in result ? <p>Substitution residual: {Array.isArray(result.verification) ? result.verification.map((v) => Math.abs(v) < 1e-10 ? '0' : v.toPrecision(4)).join(', ') : result.verification}</p> : null}</> : result.kind === 'unique' ? <><span>Solution</span><strong>x = {result.x.toPrecision(10)} · y = {result.y.toPrecision(10)}</strong><p>Verification: left sides evaluate to {result.verification.map((v) => v.toPrecision(8)).join(' and ')}.</p></> : <><span>Solution</span><strong>No unique solution</strong><p>The equations are dependent or inconsistent.</p></>}</div>
  </div>
}

function MatrixGrid({ matrix, onChange, label }: { matrix: Matrix; onChange: (matrix: Matrix) => void; label: string }) {
  const readOnly = label === 'Result matrix'
  return <div><strong>{label}</strong><div className="matrix-grid" style={{ gridTemplateColumns: `repeat(${matrix[0].length}, minmax(44px, 1fr))` }}>{matrix.flatMap((row, r) => row.map((value, c) => <input key={`${r}-${c}`} type="number" step="any" value={value} readOnly={readOnly} aria-label={`${label} row ${r + 1} column ${c + 1}`} onChange={(event) => onChange(matrix.map((line, ri) => line.map((item, ci) => ri === r && ci === c ? Number(event.target.value) : item)))} />))}</div></div>
}
function MatrixTool() {
  const [rows, setRows] = useState(2); const [columns, setColumns] = useState(2)
  const [a, setA] = useState<Matrix>([[1, 2], [3, 4]]); const [b, setB] = useState<Matrix>([[5, 6], [7, 8]])
  const [result, setResult] = useState<Matrix | string>(identity(2)); const [error, setError] = useState('')
  function resize(nextRows: number, nextColumns: number) { const fit = (matrix: Matrix) => Array.from({ length: nextRows }, (_, r) => Array.from({ length: nextColumns }, (_, c) => matrix[r]?.[c] ?? (r === c ? 1 : 0))); setRows(nextRows); setColumns(nextColumns); setA(fit(a)); setB(fit(b)) }
  function run(operation: string) { try { const next = operation === 'add' ? matrixAdd(a, b) : operation === 'subtract' ? matrixAdd(a, b, -1) : operation === 'multiply' ? matrixMultiply(a, b) : operation === 'transpose' ? transpose(a) : operation === 'determinant' ? `det(A) = ${determinant(a)}` : operation === 'inverse' ? inverse(a) : operation === 'rank' ? `rank(A) = ${matrixRank(a)}` : identity(rows); setResult(next); setError('') } catch (caught) { setError(caught instanceof Error ? caught.message : 'Matrix operation failed.') } }
  async function copy() { await navigator.clipboard.writeText(typeof result === 'string' ? result : result.map((row) => row.join('\t')).join('\n')) }
  return <div className="lab-tool matrix-tool"><header><div><span className="eyebrow">Matrix workspace</span><h2>Operate with clarity</h2></div><div className="dimension-controls"><label>Rows <select value={rows} onChange={(e) => resize(Number(e.target.value), columns)}>{[1,2,3,4].map(n => <option key={n}>{n}</option>)}</select></label><label>Columns <select value={columns} onChange={(e) => resize(rows, Number(e.target.value))}>{[1,2,3,4].map(n => <option key={n}>{n}</option>)}</select></label></div></header><div className="matrix-inputs"><MatrixGrid matrix={a} onChange={setA} label="Matrix A" /><MatrixGrid matrix={b} onChange={setB} label="Matrix B" /></div><div className="operation-row">{[['add','A + B'],['subtract','A − B'],['multiply','A × B'],['transpose','Transpose A'],['determinant','det(A)'],['inverse','Inverse A'],['rank','Rank A'],['identity','Identity']].map(([id,label]) => <button key={id} onClick={() => run(id)}>{label}</button>)}</div>{error ? <p className="field-error" role="alert">{error}</p> : null}<div className="matrix-result"><header><span>Result</span><button onClick={() => void copy()}><Copy size={16} /> Copy</button></header>{typeof result === 'string' ? <strong>{result}</strong> : <MatrixGrid matrix={result} onChange={() => {}} label="Result matrix" />}</div></div>
}

function StatisticsTool() {
  const [input, setInput] = useState('12, 15, 15, 18, 21, 24, 24, 24, 31, 36')
  const [sample, setSample] = useState(true)
  let result: ReturnType<typeof statistics> | null = null; let error = ''
  try { result = statistics(parseDataset(input), sample) } catch (caught) { error = caught instanceof Error ? caught.message : 'Could not read this dataset.' }
  const maxCount = result ? Math.max(...[...new Set(result.sorted)].map((v) => result!.sorted.filter((n) => n === v).length)) : 1
  return <div className="lab-tool stats-tool"><header><div><span className="eyebrow">Statistics</span><h2>Understand a dataset</h2></div><div className="segmented"><button className={sample ? 'active' : ''} onClick={() => setSample(true)}>Sample</button><button className={!sample ? 'active' : ''} onClick={() => setSample(false)}>Population</button></div></header><label className="dataset-input">Dataset<textarea value={input} onChange={(event) => setInput(event.target.value)} placeholder="Paste numbers separated by commas, spaces, or new lines" rows={4} /></label>{error ? <p className="field-error" role="alert">{error}</p> : result ? <><div className="stat-grid">{[['Count',result.count],['Sum',result.sum],['Mean',result.mean],['Median',result.median],['Mode',result.modes.join(', ') || 'None'],['Minimum',result.min],['Maximum',result.max],['Range',result.range],['Variance',result.variance],['Std. deviation',result.standardDeviation],['Q1',result.q1],['Q3',result.q3]].map(([label,value]) => <div key={label as string}><span>{label}</span><strong>{typeof value === 'number' ? Number(value.toPrecision(9)) : value}</strong></div>)}</div><div className="distribution" aria-label="Frequency distribution">{[...new Set(result.sorted)].map((value) => { const count = result!.sorted.filter((item) => item === value).length; return <div key={value}><span style={{ height: `${Math.max(12, count / maxCount * 100)}%` }} title={`${value}: ${count}`} /><small>{value}</small></div> })}</div></> : null}</div>
}

function ProgrammerTool() {
  const [input, setInput] = useState('42'); const [radix, setRadix] = useState<2|8|10|16>(10); const [width, setWidth] = useState<8|16|32>(8); const [signed, setSigned] = useState(false); const [operand, setOperand] = useState('3'); const [operation, setOperation] = useState<'AND'|'OR'|'XOR'|'NOT'|'SHL'|'SHR'>('AND')
  let result: ReturnType<typeof programmerRepresentations> | null = null; let error = ''
  try { result = programmerRepresentations(input, radix, width, signed) } catch (caught) { error = caught instanceof Error ? caught.message : 'Invalid number.' }
  const output = result ? bitwise(operation, result.unsigned, Number.parseInt(operand || '0', radix) || 0, width) : 0
  return <div className="lab-tool programmer-tool"><header><div><span className="eyebrow">Programmer</span><h2>See every bit</h2></div><div className="programmer-options"><select value={width} onChange={(e) => setWidth(Number(e.target.value) as 8|16|32)} aria-label="Bit width"><option value={8}>8 bit</option><option value={16}>16 bit</option><option value={32}>32 bit</option></select><label><input type="checkbox" checked={signed} onChange={(e) => setSigned(e.target.checked)} /> Signed</label></div></header><div className="base-tabs">{[[2,'BIN'],[8,'OCT'],[10,'DEC'],[16,'HEX']].map(([value,label]) => <button key={value} className={radix === value ? 'active' : ''} onClick={() => { if (result) setInput((value === 2 ? result.binary : value === 8 ? result.octal : value === 10 ? result.decimal : result.hexadecimal)); setRadix(value as 2|8|10|16) }}>{label}</button>)}</div><input className="programmer-input" value={input} onChange={(e) => setInput(e.target.value.toUpperCase())} aria-label="Programmer number input" />{error ? <p className="field-error" role="alert">{error}</p> : result ? <div className="representation-list"><div><span>BIN</span><code>{result.binary.replace(/(.{4})/g, '$1 ').trim()}</code></div><div><span>OCT</span><code>{result.octal}</code></div><div><span>DEC</span><code>{result.decimal}</code></div><div><span>HEX</span><code>{result.hexadecimal}</code></div>{result.overflow ? <p className="warning">Input overflows the selected {width}-bit range and was wrapped.</p> : null}</div> : null}<div className="bitwise-row"><select value={operation} onChange={(e) => setOperation(e.target.value as typeof operation)}>{['AND','OR','XOR','NOT','SHL','SHR'].map(op => <option key={op}>{op}</option>)}</select>{operation !== 'NOT' ? <input value={operand} onChange={(e) => setOperand(e.target.value.toUpperCase())} aria-label="Second operand or shift amount" /> : null}<span>=</span><code>{output.toString(radix).toUpperCase()}</code></div></div>
}

export function LabView() {
  const [tool, setTool] = useState<Tool>('equations')
  return <section className="lab-view" aria-label="Advanced calculation lab"><aside className="lab-selector"><header><span className="eyebrow">Lab</span><h1>Focused tools</h1><p>Choose one instrument. Nothing here is a placeholder.</p></header>{tools.map((item) => { const Icon = item.icon; return <button key={item.id} className={tool === item.id ? 'active' : ''} onClick={() => setTool(item.id)}><Icon size={19} /><span><strong>{item.name}</strong><small>{item.description}</small></span></button> })}</aside><div className="lab-stage">{tool === 'equations' ? <EquationTool /> : tool === 'matrix' ? <MatrixTool /> : tool === 'statistics' ? <StatisticsTool /> : <ProgrammerTool />}</div></section>
}
